### ISSUE TITLE
TypeError: app.use() requires middleware functions

### ISSUE THREAD

**Issue by adriagil** [JonathanBennett/prerender-redis-cache#11]
I've followed the instructions step by step but when trying to execute my Express app I get the following error:
TypeError: app.use() requires middleware functions

I'm providing process.env.REDIS_URL as well as requiring the proper package:
app.use(require('prerender-redis-cache'));

Anyone having this issue?

**Comment by thoop** [comment]
This middleware is meant for use on the Prerender server to store prerendered pages in Redis where it looks like you are trying to use this on your website. This package won't work for storing things in redis on your website.

**Comment by adriagil** [comment]
Yes true, I misunderstood the instructions and I was adding the package to my Express app but all I needed is to place it in the prerender server config file.

Thanks!
