### ISSUE TITLE
ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by abarke** [JonathanBennett/prerender-redis-cache#18]
This error is happening when using REDIS_URL=redis://u:password@my-redis-server.io:32962
```
Redis Cache Error: ReplyError: Ready check failed: NOAUTH Authentication required.
```
It happens when the redis client sends a message `client.select(connection.database);`
before `client.auth` is called on line 43.

I will submit a PR with a simple fix for this shortly.

**Comment by JonathanBennett** [comment]
Released as version 0.2.1! 

Many thanks for your PR!
