### ISSUE TITLE
Align npm versions and tags in Git repository

### ISSUE THREAD

**Issue by irnc** [JonathanBennett/prerender-redis-cache#9]
It is needed for convenience and reference. Right now source code is not tagged at all and references `0.1.3`, while latest npm release is `0.1.6`.

I usually use `npm version patch` to increment patch level and update both `package.json` and Git tab, and only after that - publish to npm.

**Comment by JonathanBennett** [comment]
Feedback noted; will get this cleaned up - thanks!

**Comment by JonathanBennett** [comment]
Finally all cleaned. Thanks!
